### ISSUE TITLE
Support polygon(mumbai) network

### ISSUE THREAD

**Issue by VasilyevAA** [bokkypoobah/WeenusTokenFaucet#5]
Hi, @bokkypoobah  !
Could you support polygon test network, please? 
I deployed contract already, but can't create PR for update readme

This is changed readme:

`<kbd><img src="images/PrincessLeiaPeachExpelsARainbowBigBang-WeenusTokenFaucet.png" /></kbd>

<br />

<hr />

# Weenus 💪 Token Faucet

An ERC20 token faucet on the Ethereum mainnet, the Ropsten, Kovan, Rinkeby and Görli testnets, and the xDai and the Polygon(Mumbai) networks.

<br />

Search in your Ethereum blockchain explorer for **WEENUS** (18 decimals), **XEENUS** (18 decimals), **YEENUS** (8 decimals) or **ZEENUS** (0 decimals).

Send a 0 value transaction from your account to the token contract addresses below on your preferred network, and these token contracts will mint 1,000 ERC20 test tokens for your account.

You will need some ethers (ETH) to pay for the network transaction fees. See [Testnet Ether Faucets](#testnet-ether-faucets) below to obtain testnet ethers.

<br />

Symbol | Decimals | Faucet Drip Rate | [Mainnet](https://etherscan.io/) | [Ropsten](https://ropsten.etherscan.io/) |  [Kovan](https://kovan.etherscan.io/) | [Rinkeby](https://rinkeby.etherscan.io/) | [Görli](https://goerli.etherscan.io/) | [xDai](https://explorer.poa.network/poa/xdai/) | [Polygon(mumbai)](https://mumbai.polygonscan.com/)
:----- | --------:| ----------------:|:------- |:------- |:------- |:----- |:----- |:----- |:-----
[WEENUS](contracts/WeenusToken.sol) | 18 | 1,000 | [0x2823589A](https://etherscan.io/address/0x2823589Ae095D99bD64dEeA80B4690313e2fB519#code) | [0x101848D5](https://ropsten.etherscan.io/address/0x101848D5C5bBca18E6b4431eEdF6B95E9ADF82FA#code) | [0xaFF4481D](https://kovan.etherscan.io/address/0xaFF4481D10270F50f203E0763e2597776068CBc5#code) | [0xaFF4481D](https://rinkeby.etherscan.io/address/0xaFF4481D10270F50f203E0763e2597776068CBc5#code) | [0xaFF4481D](https://goerli.etherscan.io/address/0xaFF4481D10270F50f203E0763e2597776068CBc5#code) | [0xE6421E9a](https://blockscout.com/poa/xdai/address/0xE6421E9aF92aca6a81C9fD0BAbacE4a9c5691c60/contracts) | [0xB293DfbD](https://mumbai.polygonscan.com/address/0xB293DfbDAfdE43cd79B54F98214402ffa895d056)
[XEENUS](contracts/XeenusToken.sol) | 18 | 1,000 | [0xeEf5E2d8](https://etherscan.io/address/0xeEf5E2d8255E973d587217f9509B416b41CA5870#code) | [0x7E0480Ca](https://ropsten.etherscan.io/address/0x7E0480Ca9fD50EB7A3855Cf53c347A1b4d6A2FF5#code) | [0x022E292b](https://kovan.etherscan.io/address/0x022E292b44B5a146F2e8ee36Ff44D3dd863C915c#code) | [0x022E292b](https://rinkeby.etherscan.io/address/0x022E292b44B5a146F2e8ee36Ff44D3dd863C915c#code)  | [0x022E292b](https://goerli.etherscan.io/address/0x022E292b44B5a146F2e8ee36Ff44D3dd863C915c#code) | [0xB6D06c9b](https://blockscout.com/poa/xdai/address/0xB6D06c9b5C4a65f389796CB713D04ac8Da6fAA01/contracts) | [0x2b3Ea076](https://mumbai.polygonscan.com/address/0x2b3Ea07688fc89cf5cD752f61D287C1570379538)
[YEENUS](contracts/YeenusToken.sol) |  8 | 1,000 | [0x187E63F9](https://etherscan.io/address/0x187E63F9eBA692A0ac98d3edE6fEb870AF0079e1#code) | [0xF6fF95D5](https://ropsten.etherscan.io/address/0xF6fF95D53E08c9660dC7820fD5A775484f77183A#code) | [0xc6fDe3FD](https://kovan.etherscan.io/address/0xc6fDe3FD2Cc2b173aEC24cc3f267cb3Cd78a26B7#code) | [0xc6fDe3FD](https://rinkeby.etherscan.io/address/0xc6fDe3FD2Cc2b173aEC24cc3f267cb3Cd78a26B7#code) | [0xc6fDe3FD](https://goerli.etherscan.io/address/0xc6fDe3FD2Cc2b173aEC24cc3f267cb3Cd78a26B7#code) | [0x0257f5d2](https://blockscout.com/poa/xdai/address/0x0257f5d2f23E41aB39F6016BF3B0010955E5F596/contracts) | [0x0e427E5a](https://mumbai.polygonscan.com/address/0x0e427E5aa094A5b7ab455383Df2C56Dae53612B0)
[ZEENUS](contracts/ZeenusToken.sol) |  0 | 1,000 | [0x0693c3a7](https://etherscan.io/address/0x0693c3a780A0a757E803a4BD76bCf43d438f8806#code) | [0xC84f8B66](https://ropsten.etherscan.io/address/0xC84f8B669Ccb91C86AB2b38060362b9956f2De52#code) | [0x1f9061B9](https://kovan.etherscan.io/address/0x1f9061B953bBa0E36BF50F21876132DcF276fC6e#code) | [0x1f9061B9](https://rinkeby.etherscan.io/address/0x1f9061B953bBa0E36BF50F21876132DcF276fC6e#code) | [0x1f9061B9](https://goerli.etherscan.io/address/0x1f9061B953bBa0E36BF50F21876132DcF276fC6e#code) | [0x81F4Ce55](https://blockscout.com/poa/xdai/address/0x81F4Ce556E4b47748ad2Ab8878FeE5054CbAB7a2/contracts) | [0x9B20B6C3](https://mumbai.polygonscan.com/address/0x9B20B6C3A60C7B5740d62A3Dcda3713Cb5435e6D)

<hr />

<br />

# Testnet Ether Faucets

Testnet   | Explorers                     | Testnet ETH Faucets
:-------- |:----------------------------- |:-------------------------
Ropsten   | https://ropsten.etherscan.io/ | https://faucet.metamask.io/<br />https://twitter.com/BokkyPooBah/status/1099498823699714048
Kovan     | https://kovan.etherscan.io/   | https://faucet.kovan.network/<br />https://github.com/kovan-testnet/faucet<br />https://faucet.kovan.radarrelay.com/
Rinkeby   | https://rinkeby.etherscan.io/ | https://faucet.rinkeby.io/<br />https://faucet.metamask.io/
Görli     | https://goerli.etherscan.io/  | https://faucet.goerli.mudit.blog/<br />https://goerli-faucet.slock.it/<br />https://bridge.goerli.com/
Polygon(mumbai)     | https://mumbai.polygonscan.com/  | https://faucet.polygon.technology/

<br />

Please submit PR with updates to the information above.

<br />

<br />

Enjoy!

(c) BokkyPooBah / Bok Consulting Pty Ltd - Sep 15 2020. The MIT Licence.
`

**Comment by bokkypoobah** [comment]
Merged. Thanks.

**Comment by bokkypoobah** [comment]
https://twitter.com/BokkyPooBah/status/1506160990324346881
